name: calculatorapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
